### ISSUE TITLE
cannot access to calendar

### ISSUE THREAD

**Issue by plailaem** [SensorsIot/Reminder-with-Google-Calender#6]
Now esp cannot access to calendar data because  this document moved temporality. How to fix this issue? , Thank you.

Serial response

Final Response:
202

<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://script.googleusercontent.com/macros/echo?user_content_key=qnWWTHt9DXZ1tntWP9HvLV69y1iRgdTjz80n_CVEj1Zh4b0hxl1eiiAWW2NLIIjNKloiycXCT9YAdz3WmjbrFSDadFHufJ5m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhE&amp;lib=MiRpYwOhLOMa4EvkRE6cDPw37LWsz9iH-">here</A>.
</BODY>
</HTML>

END OF RESPONSE

**Comment by SensorsIot** [comment]
Can you be more specific?

**Comment by plailaem** [comment]
Board : esp32 (esp8266 cannot connect google host)
ide : arduino ide 1.89
code :
..
void getCalendar() {
  Serial.println("Start Request");
  HTTPSRedirect client(httpsPort);
  if (!client.connected()) client.connect(host, httpsPort);
  calendarData = client.getData(url, host, googleRedirHost);
  Serial.println(calendarData);
}
..

Serial response picture : https://ibb.co/X2L6nWC

**Comment by SensorsIot** [comment]
It seems to be a problem on the remote side. Since I have no idea about that part I cannot help. I only can confirm that my reminder still works (But not compiled with the newest version of the ESP8266 Arduino environment. Maybe you experiment by calling the URL with your normal web browser? Then you see if there is a problem in your Arduino code or on the Google side (I use the Chrome app "ARC" for that)
